Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,8 +25,10 @@ jobs:
         chmod 700 ./cov/test.sh
         script_output=$(./cov/test.sh)
         echo "Script Output: $script_output"
-        echo "sh ./cov/test.sh" >> "$COVERAGE_FILE"
-        echo "coverage report : $COVERAGE_FILE"
+        if [ "$(echo "$script_output < 80" | bc)" -eq 1 ]; then
+            echo "Error: Coverage is less than 80%. Workflow failed."
+            exit 1
+        fi
           
 
 
