Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,9 +25,9 @@ jobs:
         chmod 700 ./cov/test.sh
         script_output=$(./cov/test.sh)
         echo "Script Output: $script_output"
-        if [ "$(echo "$script_output < 60%")" ]; then
-            echo "Error: Coverage is less than 80%. Workflow failed."
-            exit 1
+        if (( $(echo "$script_output < 80" | bc -l) )); then
+          echo "Error: Coverage is less than 80%. Workflow failed."
+          exit 1
         fi
           
 
